### ISSUE TITLE
What is the '/content/file_name.xlsx' in demo like?Could you please send a capture,thank you!

### ISSUE THREAD

**Issue by MysteryNull** [RIDWANE12/Trigonometric-Euclidean-Smoother-Interpolator-TESI-#1]

**Comment by DerrazRadhwane** [comment]
It's an Excel sheet of N columns, M rows, and a header with N labels. Each column is named with one label.

**Comment by DerrazRadhwane** [comment]
[file_name.xlsx](https://github.com/RIDWANE12/Trigonometric-Euclidean-Smoother-Interpolator-TESI-/files/11802326/file_name.xlsx)

**Comment by MysteryNull** [comment]
Thank you for your reply!

**Comment by MysteryNull** [comment]
> [file_name.xlsx](https://github.com/RIDWANE12/Trigonometric-Euclidean-Smoother-Interpolator-TESI-/files/11802326/file_name.xlsx)

I try running the demo code by using the file you provided.But some bugs still exist.Here is the code and the result.
![QQ截图20230621094348](https://github.com/RIDWANE12/Trigonometric-Euclidean-Smoother-Interpolator-TESI-/assets/91356383/cd5dc4b6-f057-40c1-968c-02237a18011c)
![QQ截图20230621094406](https://github.com/RIDWANE12/Trigonometric-Euclidean-Smoother-Interpolator-TESI-/assets/91356383/b63b4504-553d-4016-aea5-76b211fbbb76)
![QQ截图20230621094628](https://github.com/RIDWANE12/Trigonometric-Euclidean-Smoother-Interpolator-TESI-/assets/91356383/fa4e1d04-31eb-4491-bb94-47a901d6566a)

**Comment by RIDWANE12** [comment]
Welcome!
Yes, when the data set contains duplicate values, such as 0.6 and 0.6 or 0.3 and 0.3 , respectively in the same variable, as shown above, then y2 will be 0. Devision by zero is a mathematical error in Python and the interpolation output is NAN for this reason The cells between the duplicate values are blank. NAN value / blank cells must be zero. Simply fill in the blank cells with a zero. Just use your own dataset. A new version of the package will be released soon to address this and similar errors. Thank you very much!
